name: Do Work

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  do-work:
    runs-on: ubuntu-latest

    steps:
      - name: Do Work
        uses: dongchengjie/proxy_workers@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: subs/
