name: Do Work

on:
  workflow_dispatch:

jobs:
  do-work:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch subscribe files
        uses: dongchengjie/proxy_workers@main
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: subs/
